"""Zentrale UI-Texte für ConnectFour Studio (aus cfs_lang.py übernommen).

Qt-Port: Inhalt (STRINGS/LEVEL_NAMES/t/tf/...) unverändert; nur lang.cfg
liegt jetzt im Benutzerordner (cfs_core.paths.user_dir()).


Regel: Jeder sichtbare Text im Programm steht hier als Schlüssel.
Code nutzt nur noch STRINGS[lang][schlüssel]. Neue Sprache = nur dieses
Dict ergänzen, keine Logik anfassen.

Stand: de vollständig, en als Arbeitsübersetzung (bitte gegenlesen).
"""

import os

STRINGS = {
    "de": {
        # Menüs
        "menu_file": "Datei",
        "menu_view": "Ansicht",
        "menu_settings": "Einstellungen",
        "menu_commands": "Kommandos",
        "menu_help": "Hilfe",
        # Datei
        "new_game": "Neues Spiel",
        "new_random": "Neu mit Zufallsstellung...",
        "load_position": "Stellung laden...",
        "save_position": "Stellung speichern...",
        "quick_save": "Schnell speichern (F3)",
        "quick_load": "Schnell laden (F4)",
        "quit": "Ende",
        # Ansicht
        "ghost_stone": "Ghost-Stein",
        "drop_animation": "Drop-Animation",
        "show_last_move": "letzten Zug zeigen",
        "score_onoff": "Spielstand ein/aus",
        "score_reset": "Spielstand reset",
        # Einstellungen
        "computer_level": "Computer-Stufe",
        "human_computer": "Mensch-Computer",
        "two_player": "2-Spieler (beide Mensch)",
        "selfplay": "Computer-Computer (ausspielen)",
        "match": "Computer-Computer Match...",
        "stop_autoplay": "Stop Auto Play",
        "stone_set": "Stein-Set",
        "prev_set": "vorheriges Set",
        "next_set": "nächstes Set",
        # Kommandos
        "first_move": "erster Zug",
        "move_back": "Zug zurück",
        "move_forward": "Zug vor",
        "last_move": "letzter Zug",
        "engine_move": "ziehen (Computer)",
        "score_all": "alle Züge bewerten (1x)",
        "permanent_analysis": "Dauer-Analyse",
        # Hilfe
        "help_contents": "Inhalt",
        "help_info": "Info",
        "lang_menu": "Sprache",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_es": "Español",
        "lang_nl": "Nederlands",
        "lang_it": "Italiano",
        # Infobox
        "info_turn": "Am Zuge",
        "info_box": "Info",
        "info_move": "Zug",
        "info_level": "Stufe",
        "info_depth": "Tiefe",
        "info_value": "Wert",
        "info_nodes": "Knoten",
        "info_time": "Zeit",
        "info_nodes_per_sec": "Tempo",
        "info_book": "Quelle",
        "info_human": "Mensch",
        "depth_full": "Voll",
        "depth_book": "Buch",
        "depth_search": "Suche",
        "book_from_book": "Buch",
        "book_computed": "berechnet",
        # Spielstand
        "score_box": "Spielstand",
        "score_on": "An/Aus",
        "score_reset_btn": "Reset",
        # Auswahlwerte / Stufen
        "level_human": "Mensch",
        # Buttons unterm Brett
        "btn_new": "Neu",
        "btn_first": "<<",
        "btn_back": "<",
        "btn_forward": ">",
        "btn_last": ">>",
        "btn_move": "Ziehen",
        "btn_analyze": "Analyse",
        # Dialoge: Datei laden/speichern, Fehler, Zufallsstellung, Match
        "file_open_title": "Stellung laden",
        "file_save_title": "Stellung speichern",
        "file_filter_c4": "ConnectFour-Stellung",
        "file_filter_all": "Alle",
        "error_title": "Fehler",
        "info_title": "Info",
        "new_random_title": "Neues Spiel mit Zufallsstellung",
        "new_random_stones": "Steine auf dem Brett:",
        "new_random_result": "Ergebnis (Spieler am Zug):",
        "new_random_any": "Egal",
        "new_random_win": "Gewinn",
        "new_random_draw": "Unentschieden",
        "new_random_loss": "Verlust",
        "new_random_hint": "Gewinn/Verlust wird per Engine geprüft.",
        "btn_ok": "OK",
        "btn_cancel": "Abbrechen",
        "btn_close": "Schließen",
        "btn_copy": "Kopieren",
        "btn_start": "Start",
        "btn_stop": "Stop",
        # Status-/Fehlermeldungen
        "status_thinking": "Computer denkt...",
        "status_computer_move": "Computer zog {col} in {sec} s.",
        "status_aborted": "Abgebrochen.",
        "status_stopped": "Angehalten (Ergebnis wird verworfen).",
        "status_wait_thinking": "Computer denkt noch – bitte warten.",
        "status_game_over_new": "Spiel beendet – Neu starten.",
        "status_column_full": "Spalte {col} ist voll.",
        "status_match_running": "Computer-Computer Match läuft – erst anhalten (Stop).",
        "status_selfplay_running": "Computer-Computer läuft – erst anderen Modus wählen.",
        "status_new_game": "Neues Spiel.",
        "status_no_position_found": "Keine passende Stellung gefunden – Egal versuchen.",
        "status_search_random": "Suche Zufallsstellung ({n} Steine, {wish})...",
        "status_scores_off": "Bewertung aus (1-7).",
        "status_analysis_off": "Analyse aus.",
        "status_book_loaded": "Buch: {book}.",
        "status_saved": "Gespeichert: {path}",
        "status_loaded": "Geladen: {path}",
        "status_no_quicksave": "Nichts gespeichert (erst F3 drücken).",
        "status_set_changed": "Stein-Set {no} – {name}.",
        "status_level_changed": "Stufe: {label}.",
        "status_computer_error": "Computer-Fehler: {err}",
        "status_discarded": "Verworfen: Stellung hat sich während der Berechnung geändert.",
        "status_load_stopped_thinking": "Computer denkt noch – erst angehalten, dann laden.",
        # Spielstand
        "score_box": "Spielstand",
        "score_on": "An/Aus",
        "score_reset_btn": "Reset",
        # Auswahlwerte / Stufen
        "level_human": "Mensch",
        # Dialoge, Match, Statuszeile (UI-Umstellung 04.10.2026)
        "status_ready": "Bereit.",
        "status_selfplay_running_stop": "Computer-Computer läuft – erst anhalten (Stop).",
        "status_random_done": "Zufallsstellung: {n} Steine ({wish}).",
        "status_eval_aborted": "Bewertung abgebrochen.",
        "status_game_end": "Spielende: {msg}",
        "msg_draw": "Unentschieden!",
        "msg_wins": "{who} gewinnt!",
        "color_yellow": "Gelb",
        "color_red": "Rot",
        "value_draw": "Remis",
        "status_analysis_error": "Analyse-Fehler: {err}",
        "status_analysis_done": "Analyse: Spalte {col} ({score:+d}) in {sec} s.",
        "status_selfplay_fixed": "Computer-Computer (ausspielen): Stufe fest.",
        "status_hc_level": "Mensch-Computer: {label}.",
        "status_hc_mode": "Mensch-Computer-Modus ({label}).",
        "status_selfplay_playing": "Computer-Computer (ausspielen) spielt...",
        "status_stop_before_match": "Erst anhalten (Stop), dann Match einstellen.",
        "status_removed_hash": "Entfernt: kein Hashtabellen-Knopf mehr.",
        "status_removed_gallery": "Galerie entfernt – Sets im Menü.",
        "status_two_player": "2-Spieler-Modus.",
        "status_autoanalysis_off": "Dauer-Analyse aus (1-7).",
        "status_autoanalysis_on": "Dauer-Analyse an.",
        "status_quick_saved": "Schnell gespeichert (F3): {n} Züge.",
        "status_quick_loaded": "Schnell geladen (F4): {name}.",
        "status_menu_opened": "Menü {name} ({src}).",
        "title_quick_save": "Schnell speichern",
        "title_quick_load": "Schnell laden",
        "title_book": "Buch",
        "err_book_load": "Buch konnte nicht geladen werden:\n{err}",
        "err_start_position": "Startstellung konnte nicht geladen werden:",
        "err_no_legal_move": "kein legaler Zug",
        "player_n": "Spieler {n}",
        "book_name_12": "12-ply-dist (Gewinn + Zugzahl bis Ende)",
        "set_menu_item": "Stein-Set {no} – {name}",
        "acc_pgup": "Bild hoch",
        "acc_pgdn": "Bild runter",
        "acc_up": "Pfeil hoch",
        "acc_down": "Pfeil runter",
        "acc_left": "Pfeil links",
        "acc_right": "Pfeil rechts",
        "match_title": "Computer-Computer Match",
        "label_yellow": "Gelb:",
        "label_red": "Rot:",
        "match_games": "Partien (1–10000):",
        "user_own_psw": " (eigene p,s,w)",
        "match_hint": "p = % perfekte Züge (Rest patzt), s = Verlustschutz (kein Patzer, der in ≤ s Gegnerzügen verliert), w = Siegsschutz (Gewinn in ≤ w Zügen geht immer vor).",
        "match_swap": "Farbwechsel nach jeder Partie",
        "match_tempo": "Tempo:",
        "tempo_normal": "Normal",
        "tempo_fast": "Schnell",
        "tempo_turbo": "Nur Ergebnisse (Turbo)",
        "match_result_label": "Endergebnis (kopierbar):",
        "match_status_line": "Computer-Computer Match {nr}/{games} | Gelb ({g}) - Rot ({r}) | {score} | {elo}",
        "match_none": "Kein Match aktiv.",
        "match_state_done": "Beendet.",
        "match_state_aborted": "Abgebrochen.",
        "match_state_running": "Läuft...",
        "match_live": "Partie {nr}/{games} – {state}\nGelb ({g}) – Rot ({r}): {score}  Elo {elo}",
        "match_no_result": "Kein Computer-Computer Match gespielt.",
        "match_result_text": "{a} - {b} = {pg}-{pr} (+{w}/={d}/-{l})  Elo-Differenz = {elo}\nPartien: {done}/{games} ({state}), Farbwechsel: {swap}",
        "match_aborted_lc": "abgebrochen",
        "match_finished_lc": "beendet",
        "onoff_on": "an",
        "onoff_off": "aus",
        "match_ended_status": "Computer-Computer Match beendet: {res}",
        "match_stopped_status": "Computer-Computer Match angehalten. {res}",
        "match_next_in": "  (Weiter in 3 s …)",
        "stand_head": "Mensch vs {x}",
        "stand_head_default": "Mensch vs Computer",
        "stand_sub": "(+{w}/={d}/-{l}) · {n} Partien",
        "side_computer": "Computer ({label})",
    },
    "en": {
        # Menus
        "menu_file": "File",
        "menu_view": "View",
        "menu_settings": "Settings",
        "menu_commands": "Commands",
        "menu_help": "Help",
        # File
        "new_game": "New game",
        "new_random": "New with random position...",
        "load_position": "Load position...",
        "save_position": "Save position...",
        "quick_save": "Quick save (F3)",
        "quick_load": "Quick load (F4)",
        "quit": "Quit",
        # View
        "ghost_stone": "Ghost stone",
        "drop_animation": "Drop animation",
        "show_last_move": "Show last move",
        "score_onoff": "Score on/off",
        "score_reset": "Reset score",
        # Settings
        "computer_level": "Computer level",
        "human_computer": "Human-Computer",
        "two_player": "2 players (both human)",
        "selfplay": "Computer-Computer (play out)",
        "match": "Computer-Computer match...",
        "stop_autoplay": "Stop auto play",
        "stone_set": "Stone set",
        "prev_set": "Previous set",
        "next_set": "Next set",
        # Commands
        "first_move": "First move",
        "move_back": "Move back",
        "move_forward": "Move forward",
        "last_move": "Last move",
        "engine_move": "Move (computer)",
        "score_all": "Evaluate all moves (1x)",
        "permanent_analysis": "Permanent analysis",
        # Help
        "help_contents": "Contents",
        "help_info": "Info",
        "lang_menu": "Language",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_es": "Español",
        "lang_nl": "Nederlands",
        "lang_it": "Italiano",
        # Info box
        "info_turn": "To move",
        "info_box": "Info",
        "info_move": "Move",
        "info_level": "Level",
        "info_depth": "Depth",
        "info_value": "Value",
        "info_nodes": "Nodes",
        "info_time": "Time",
        "info_nodes_per_sec": "Speed",
        "info_book": "Source",
        "info_human": "Human",
        "depth_full": "Full",
        "depth_book": "Book",
        "depth_search": "Search",
        "book_from_book": "Book",
        "book_computed": "computed",
        # Score
        "score_box": "Score",
        "score_on": "On/Off",
        "score_reset_btn": "Reset",
        # Option values / levels
        "level_human": "Human",
        # Buttons below the board
        "btn_new": "New",
        "btn_first": "<<",
        "btn_back": "<",
        "btn_forward": ">",
        "btn_last": ">>",
        "btn_move": "Move",
        "btn_analyze": "Analyze",
        # Dialogs: file open/save, errors, random position, match
        "file_open_title": "Load position",
        "file_save_title": "Save position",
        "file_filter_c4": "ConnectFour position",
        "file_filter_all": "All",
        "error_title": "Error",
        "info_title": "Info",
        "new_random_title": "New game with random position",
        "new_random_stones": "Stones on the board:",
        "new_random_result": "Result (player to move):",
        "new_random_any": "Any",
        "new_random_win": "Win",
        "new_random_draw": "Draw",
        "new_random_loss": "Loss",
        "new_random_hint": "Win/loss is checked by the engine.",
        "btn_ok": "OK",
        "btn_cancel": "Cancel",
        "btn_close": "Close",
        "btn_copy": "Copy",
        "btn_start": "Start",
        "btn_stop": "Stop",
        # Status/error messages
        "status_thinking": "Computer is thinking...",
        "status_computer_move": "Computer played {col} in {sec} s.",
        "status_aborted": "Aborted.",
        "status_stopped": "Stopped (result discarded).",
        "status_wait_thinking": "Computer is still thinking – please wait.",
        "status_game_over_new": "Game over – start a new game.",
        "status_column_full": "Column {col} is full.",
        "status_match_running": "Computer-Computer match is running – stop it first.",
        "status_selfplay_running": "Computer-Computer is running – choose another mode first.",
        "status_new_game": "New game.",
        "status_no_position_found": "No matching position found – try Any.",
        "status_search_random": "Searching random position ({n} stones, {wish})...",
        "status_scores_off": "Scores off (1-7).",
        "status_analysis_off": "Analysis off.",
        "status_book_loaded": "Book: {book}.",
        "status_saved": "Saved: {path}",
        "status_loaded": "Loaded: {path}",
        "status_no_quicksave": "Nothing saved (press F3 first).",
        "status_set_changed": "Stone set {no} – {name}.",
        "status_level_changed": "Level: {label}.",
        "status_computer_error": "Computer error: {err}",
        "status_discarded": "Discarded: position changed during calculation.",
        "status_load_stopped_thinking": "Computer is still thinking – stop it first, then load.",
        # Score
        "score_box": "Score",
        "score_on": "On/Off",
        "score_reset_btn": "Reset",
        # Option values / levels
        "level_human": "Human",
        # Dialoge, Match, Statuszeile (UI-Umstellung 04.10.2026)
        "status_ready": "Ready.",
        "status_selfplay_running_stop": "Computer-Computer is running – stop it first.",
        "status_random_done": "Random position: {n} stones ({wish}).",
        "status_eval_aborted": "Evaluation aborted.",
        "status_game_end": "Game over: {msg}",
        "msg_draw": "Draw!",
        "msg_wins": "{who} wins!",
        "color_yellow": "Yellow",
        "color_red": "Red",
        "value_draw": "Draw",
        "status_analysis_error": "Analysis error: {err}",
        "status_analysis_done": "Analysis: column {col} ({score:+d}) in {sec} s.",
        "status_selfplay_fixed": "Computer-Computer (play out): fixed level.",
        "status_hc_level": "Human-Computer: {label}.",
        "status_hc_mode": "Human-Computer mode ({label}).",
        "status_selfplay_playing": "Computer-Computer (play out) is playing...",
        "status_stop_before_match": "Stop first, then set up the match.",
        "status_removed_hash": "Removed: no hash table button any more.",
        "status_removed_gallery": "Gallery removed – sets are in the menu.",
        "status_two_player": "2-player mode.",
        "status_autoanalysis_off": "Permanent analysis off (1-7).",
        "status_autoanalysis_on": "Permanent analysis on.",
        "status_quick_saved": "Quick saved (F3): {n} moves.",
        "status_quick_loaded": "Quick loaded (F4): {name}.",
        "status_menu_opened": "Menu {name} ({src}).",
        "title_quick_save": "Quick save",
        "title_quick_load": "Quick load",
        "title_book": "Book",
        "err_book_load": "The book could not be loaded:\n{err}",
        "err_start_position": "The start position could not be loaded:",
        "err_no_legal_move": "no legal move",
        "player_n": "Player {n}",
        "book_name_12": "12-ply-dist (win + moves to the end)",
        "set_menu_item": "Stone set {no} – {name}",
        "acc_pgup": "Page Up",
        "acc_pgdn": "Page Down",
        "acc_up": "Up",
        "acc_down": "Down",
        "acc_left": "Left",
        "acc_right": "Right",
        "match_title": "Computer-Computer match",
        "label_yellow": "Yellow:",
        "label_red": "Red:",
        "match_games": "Games (1–10000):",
        "user_own_psw": " (own p,s,w)",
        "match_hint": "p = % perfect moves (the rest are blunders), s = loss protection (no blunder that loses within <= s opponent moves), w = win priority (a win within <= w moves always comes first).",
        "match_swap": "Swap colors after every game",
        "match_tempo": "Speed:",
        "tempo_normal": "Normal",
        "tempo_fast": "Fast",
        "tempo_turbo": "Results only (Turbo)",
        "match_result_label": "Final result (copyable):",
        "match_status_line": "Computer-Computer match {nr}/{games} | Yellow ({g}) - Red ({r}) | {score} | {elo}",
        "match_none": "No match active.",
        "match_state_done": "Finished.",
        "match_state_aborted": "Aborted.",
        "match_state_running": "Running...",
        "match_live": "Game {nr}/{games} – {state}\nYellow ({g}) – Red ({r}): {score}  Elo {elo}",
        "match_no_result": "No Computer-Computer match played.",
        "match_result_text": "{a} - {b} = {pg}-{pr} (+{w}/={d}/-{l})  Elo difference = {elo}\nGames: {done}/{games} ({state}), color swap: {swap}",
        "match_aborted_lc": "aborted",
        "match_finished_lc": "finished",
        "onoff_on": "on",
        "onoff_off": "off",
        "match_ended_status": "Computer-Computer match finished: {res}",
        "match_stopped_status": "Computer-Computer match stopped. {res}",
        "match_next_in": "  (Next game in 3 s ...)",
        "stand_head": "Human vs {x}",
        "stand_head_default": "Human vs Computer",
        "stand_sub": "(+{w}/={d}/-{l}) · {n} games",
        "side_computer": "Computer ({label})",
    },
    # Platzhalter (04.10.2026): Fallback Deutsch, bis Übersetzungen stehen.
    "fr": {
        # Français (04.10.2026), Quelle: en
        "menu_file": "Fichier",
        "menu_view": "Affichage",
        "menu_settings": "Paramètres",
        "menu_commands": "Commandes",
        "menu_help": "Aide",
        "new_game": "Nouvelle partie",
        "new_random": "Nouvelle avec position aléatoire...",
        "load_position": "Charger une position...",
        "save_position": "Enregistrer la position...",
        "quick_save": "Sauvegarde rapide (F3)",
        "quick_load": "Chargement rapide (F4)",
        "quit": "Quitter",
        "ghost_stone": "Pion fantôme",
        "drop_animation": "Animation de chute",
        "show_last_move": "Afficher le dernier coup",
        "score_onoff": "Score activé/désactivé",
        "score_reset": "Réinitialiser le score",
        "computer_level": "Niveau de l'ordinateur",
        "human_computer": "Humain-Ordinateur",
        "two_player": "2 joueurs (deux humains)",
        "selfplay": "Ordinateur-Ordinateur (jouer jusqu'au bout)",
        "match": "Match Ordinateur-Ordinateur...",
        "stop_autoplay": "Arrêter le jeu automatique",
        "stone_set": "Jeu de pions",
        "prev_set": "Jeu précédent",
        "next_set": "Jeu suivant",
        "first_move": "Premier coup",
        "move_back": "Coup précédent",
        "move_forward": "Coup suivant",
        "last_move": "Dernier coup",
        "engine_move": "Jouer (ordinateur)",
        "score_all": "Évaluer tous les coups (1x)",
        "permanent_analysis": "Analyse permanente",
        "help_contents": "Sommaire",
        "help_info": "Informations",
        "lang_menu": "Langue",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_es": "Español",
        "lang_nl": "Nederlands",
        "lang_it": "Italiano",
        "info_turn": "Au trait",
        "info_box": "Informations",
        "info_move": "Coup",
        "info_level": "Niveau",
        "info_depth": "Profondeur",
        "info_value": "Valeur",
        "info_nodes": "Nœuds",
        "info_time": "Temps",
        "info_nodes_per_sec": "Vitesse",
        "info_book": "Source",
        "info_human": "Humain",
        "depth_full": "Complète",
        "depth_book": "Livre",
        "depth_search": "Recherche",
        "book_from_book": "Livre",
        "book_computed": "calculé",
        "score_box": "Score",
        "score_on": "Oui/Non",
        "score_reset_btn": "Réinit.",
        "level_human": "Humain",
        "btn_new": "Nouvelle",
        "btn_first": "<<",
        "btn_back": "<",
        "btn_forward": ">",
        "btn_last": ">>",
        "btn_move": "Jouer",
        "btn_analyze": "Analyser",
        "file_open_title": "Charger une position",
        "file_save_title": "Enregistrer la position",
        "file_filter_c4": "Position ConnectFour",
        "file_filter_all": "Tous",
        "error_title": "Erreur",
        "info_title": "Informations",
        "new_random_title": "Nouvelle partie avec position aléatoire",
        "new_random_stones": "Pions sur le plateau :",
        "new_random_result": "Résultat (joueur au trait) :",
        "new_random_any": "Peu importe",
        "new_random_win": "Victoire",
        "new_random_draw": "Nulle",
        "new_random_loss": "Défaite",
        "new_random_hint": "Le moteur vérifie la victoire ou la défaite.",
        "btn_ok": "OK",
        "btn_cancel": "Annuler",
        "btn_close": "Fermer",
        "btn_copy": "Copier",
        "btn_start": "Démarrer",
        "btn_stop": "Arrêter",
        "status_thinking": "L'ordinateur réfléchit...",
        "status_computer_move": "L'ordinateur a joué {col} en {sec} s.",
        "status_aborted": "Interrompu.",
        "status_stopped": "Arrêté (résultat ignoré).",
        "status_wait_thinking": "L'ordinateur réfléchit encore – veuillez patienter.",
        "status_game_over_new": "Partie terminée – lancez une nouvelle partie.",
        "status_column_full": "La colonne {col} est pleine.",
        "status_match_running": "Le match Ordinateur-Ordinateur est en cours – arrêtez-le d'abord.",
        "status_selfplay_running": "Ordinateur-Ordinateur est en cours – choisissez d'abord un autre mode.",
        "status_new_game": "Nouvelle partie.",
        "status_no_position_found": "Aucune position adaptée trouvée – essayez Peu importe.",
        "status_search_random": "Recherche d'une position aléatoire ({n} pions, {wish})...",
        "status_scores_off": "Évaluation désactivée (1-7).",
        "status_analysis_off": "Analyse désactivée.",
        "status_book_loaded": "Livre : {book}.",
        "status_saved": "Enregistré : {path}",
        "status_loaded": "Chargé : {path}",
        "status_no_quicksave": "Rien n'est enregistré (appuyez d'abord sur F3).",
        "status_set_changed": "Jeu de pions {no} – {name}.",
        "status_level_changed": "Niveau : {label}.",
        "status_computer_error": "Erreur de l'ordinateur : {err}",
        "status_discarded": "Ignoré : la position a changé pendant le calcul.",
        "status_load_stopped_thinking": "L'ordinateur réfléchit encore – arrêtez-le d'abord, puis chargez.",
        "status_ready": "Prêt.",
        "status_selfplay_running_stop": "Ordinateur-Ordinateur est en cours – arrêtez-le d'abord.",
        "status_random_done": "Position aléatoire : {n} pions ({wish}).",
        "status_eval_aborted": "Évaluation interrompue.",
        "status_game_end": "Fin de partie : {msg}",
        "msg_draw": "Partie nulle !",
        "msg_wins": "{who} gagne !",
        "color_yellow": "Jaune",
        "color_red": "Rouge",
        "value_draw": "Nulle",
        "status_analysis_error": "Erreur d'analyse : {err}",
        "status_analysis_done": "Analyse : colonne {col} ({score:+d}) en {sec} s.",
        "status_selfplay_fixed": "Ordinateur-Ordinateur (jouer jusqu'au bout) : niveau fixe.",
        "status_hc_level": "Humain-Ordinateur : {label}.",
        "status_hc_mode": "Mode Humain-Ordinateur ({label}).",
        "status_selfplay_playing": "Ordinateur-Ordinateur (jouer jusqu'au bout) joue...",
        "status_stop_before_match": "Arrêtez d'abord, puis configurez le match.",
        "status_removed_hash": "Supprimé : plus de bouton de table de hachage.",
        "status_removed_gallery": "Galerie supprimée – les jeux de pions sont dans le menu.",
        "status_two_player": "Mode 2 joueurs.",
        "status_autoanalysis_off": "Analyse permanente désactivée (1-7).",
        "status_autoanalysis_on": "Analyse permanente activée.",
        "status_quick_saved": "Sauvegarde rapide (F3) : {n} coups.",
        "status_quick_loaded": "Chargement rapide (F4) : {name}.",
        "status_menu_opened": "Menu {name} ({src}).",
        "title_quick_save": "Sauvegarde rapide",
        "title_quick_load": "Chargement rapide",
        "title_book": "Livre",
        "err_book_load": "Le livre n'a pas pu être chargé :\n{err}",
        "err_start_position": "La position de départ n'a pas pu être chargée :",
        "err_no_legal_move": "aucun coup légal",
        "player_n": "Joueur {n}",
        "book_name_12": "12-ply-dist (victoire + coups jusqu'à la fin)",
        "set_menu_item": "Jeu de pions {no} – {name}",
        "acc_pgup": "Page préc.",
        "acc_pgdn": "Page suiv.",
        "acc_up": "Haut",
        "acc_down": "Bas",
        "acc_left": "Gauche",
        "acc_right": "Droite",
        "match_title": "Match Ordinateur-Ordinateur",
        "label_yellow": "Jaune :",
        "label_red": "Rouge :",
        "match_games": "Parties (1–10000) :",
        "user_own_psw": " (p,s,w personnalisés)",
        "match_hint": "p = % de coups parfaits (les autres sont des erreurs), s = protection contre la défaite (aucune erreur qui perd en <= s coups de l'adversaire), w = priorité de victoire (une victoire en <= w coups passe toujours en premier).",
        "match_swap": "Changer de couleur après chaque partie",
        "match_tempo": "Vitesse :",
        "tempo_normal": "Normal",
        "tempo_fast": "Rapide",
        "tempo_turbo": "Résultats seulement (Turbo)",
        "match_result_label": "Résultat final (copiable) :",
        "match_status_line": "Match Ordinateur-Ordinateur {nr}/{games} | Jaune ({g}) - Rouge ({r}) | {score} | {elo}",
        "match_none": "Aucun match actif.",
        "match_state_done": "Terminé.",
        "match_state_aborted": "Interrompu.",
        "match_state_running": "En cours...",
        "match_live": "Partie {nr}/{games} – {state}\nJaune ({g}) – Rouge ({r}) : {score}  Elo {elo}",
        "match_no_result": "Aucun match Ordinateur-Ordinateur n'a été joué.",
        "match_result_text": "{a} - {b} = {pg}-{pr} (+{w}/={d}/-{l})  Différence Elo = {elo}\nParties : {done}/{games} ({state}), changement de couleur : {swap}",
        "match_aborted_lc": "interrompu",
        "match_finished_lc": "terminé",
        "onoff_on": "oui",
        "onoff_off": "non",
        "match_ended_status": "Match Ordinateur-Ordinateur terminé : {res}",
        "match_stopped_status": "Match Ordinateur-Ordinateur arrêté. {res}",
        "match_next_in": "  (Partie suivante dans 3 s ...)",
        "stand_head": "Humain vs {x}",
        "stand_head_default": "Humain vs Ordinateur",
        "stand_sub": "(+{w}/={d}/-{l}) · {n} parties",
        "side_computer": "Ordinateur ({label})",
    },
    "es": {
        # Español (04.10.2026), Quelle: en
        "menu_file": "Archivo",
        "menu_view": "Ver",
        "menu_settings": "Configuración",
        "menu_commands": "Comandos",
        "menu_help": "Ayuda",
        "new_game": "Nueva partida",
        "new_random": "Nueva con posición aleatoria...",
        "load_position": "Cargar posición...",
        "save_position": "Guardar posición...",
        "quick_save": "Guardado rápido (F3)",
        "quick_load": "Carga rápida (F4)",
        "quit": "Salir",
        "ghost_stone": "Ficha fantasma",
        "drop_animation": "Animación de caída",
        "show_last_move": "Mostrar última jugada",
        "score_onoff": "Marcador sí/no",
        "score_reset": "Reiniciar marcador",
        "computer_level": "Nivel del ordenador",
        "human_computer": "Humano-Ordenador",
        "two_player": "2 jugadores (ambos humanos)",
        "selfplay": "Ordenador-Ordenador (jugar hasta el final)",
        "match": "Partido Ordenador-Ordenador...",
        "stop_autoplay": "Detener juego automático",
        "stone_set": "Juego de fichas",
        "prev_set": "Juego anterior",
        "next_set": "Juego siguiente",
        "first_move": "Primera jugada",
        "move_back": "Jugada atrás",
        "move_forward": "Jugada adelante",
        "last_move": "Última jugada",
        "engine_move": "Jugar (ordenador)",
        "score_all": "Evaluar todas las jugadas (1x)",
        "permanent_analysis": "Análisis permanente",
        "help_contents": "Contenido",
        "help_info": "Información",
        "lang_menu": "Idioma",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_es": "Español",
        "lang_nl": "Nederlands",
        "lang_it": "Italiano",
        "info_turn": "Turno",
        "info_box": "Información",
        "info_move": "Jugada",
        "info_level": "Nivel",
        "info_depth": "Profundidad",
        "info_value": "Valor",
        "info_nodes": "Nodos",
        "info_time": "Tiempo",
        "info_nodes_per_sec": "Velocidad",
        "info_book": "Fuente",
        "info_human": "Humano",
        "depth_full": "Completa",
        "depth_book": "Libro",
        "depth_search": "Búsqueda",
        "book_from_book": "Libro",
        "book_computed": "calculado",
        "score_box": "Marcador",
        "score_on": "Sí/No",
        "score_reset_btn": "Reiniciar",
        "level_human": "Humano",
        "btn_new": "Nueva",
        "btn_first": "<<",
        "btn_back": "<",
        "btn_forward": ">",
        "btn_last": ">>",
        "btn_move": "Jugar",
        "btn_analyze": "Analizar",
        "file_open_title": "Cargar posición",
        "file_save_title": "Guardar posición",
        "file_filter_c4": "Posición de ConnectFour",
        "file_filter_all": "Todos",
        "error_title": "Error",
        "info_title": "Información",
        "new_random_title": "Nueva partida con posición aleatoria",
        "new_random_stones": "Fichas en el tablero:",
        "new_random_result": "Resultado (jugador al que le toca):",
        "new_random_any": "Cualquiera",
        "new_random_win": "Victoria",
        "new_random_draw": "Tablas",
        "new_random_loss": "Derrota",
        "new_random_hint": "El motor comprueba la victoria o la derrota.",
        "btn_ok": "OK",
        "btn_cancel": "Cancelar",
        "btn_close": "Cerrar",
        "btn_copy": "Copiar",
        "btn_start": "Iniciar",
        "btn_stop": "Detener",
        "status_thinking": "El ordenador está pensando...",
        "status_computer_move": "El ordenador jugó {col} en {sec} s.",
        "status_aborted": "Cancelado.",
        "status_stopped": "Detenido (resultado descartado).",
        "status_wait_thinking": "El ordenador aún está pensando – espere, por favor.",
        "status_game_over_new": "Fin de la partida – inicie una nueva.",
        "status_column_full": "La columna {col} está llena.",
        "status_match_running": "El partido Ordenador-Ordenador está en curso – deténgalo primero.",
        "status_selfplay_running": "Ordenador-Ordenador está en curso – elija primero otro modo.",
        "status_new_game": "Nueva partida.",
        "status_no_position_found": "No se encontró ninguna posición adecuada – pruebe con Cualquiera.",
        "status_search_random": "Buscando posición aleatoria ({n} fichas, {wish})...",
        "status_scores_off": "Evaluación desactivada (1-7).",
        "status_analysis_off": "Análisis desactivado.",
        "status_book_loaded": "Libro: {book}.",
        "status_saved": "Guardado: {path}",
        "status_loaded": "Cargado: {path}",
        "status_no_quicksave": "Nada guardado (pulse F3 primero).",
        "status_set_changed": "Juego de fichas {no} – {name}.",
        "status_level_changed": "Nivel: {label}.",
        "status_computer_error": "Error del ordenador: {err}",
        "status_discarded": "Descartado: la posición cambió durante el cálculo.",
        "status_load_stopped_thinking": "El ordenador aún está pensando – deténgalo primero y luego cargue.",
        "status_ready": "Listo.",
        "status_selfplay_running_stop": "Ordenador-Ordenador está en curso – deténgalo primero.",
        "status_random_done": "Posición aleatoria: {n} fichas ({wish}).",
        "status_eval_aborted": "Evaluación cancelada.",
        "status_game_end": "Fin de la partida: {msg}",
        "msg_draw": "¡Tablas!",
        "msg_wins": "¡{who} gana!",
        "color_yellow": "Amarillo",
        "color_red": "Rojo",
        "value_draw": "Tablas",
        "status_analysis_error": "Error de análisis: {err}",
        "status_analysis_done": "Análisis: columna {col} ({score:+d}) en {sec} s.",
        "status_selfplay_fixed": "Ordenador-Ordenador (jugar hasta el final): nivel fijo.",
        "status_hc_level": "Humano-Ordenador: {label}.",
        "status_hc_mode": "Modo Humano-Ordenador ({label}).",
        "status_selfplay_playing": "Ordenador-Ordenador (jugar hasta el final) está jugando...",
        "status_stop_before_match": "Detenga primero y luego configure el partido.",
        "status_removed_hash": "Eliminado: ya no hay botón de tabla hash.",
        "status_removed_gallery": "Galería eliminada – los juegos de fichas están en el menú.",
        "status_two_player": "Modo de 2 jugadores.",
        "status_autoanalysis_off": "Análisis permanente desactivado (1-7).",
        "status_autoanalysis_on": "Análisis permanente activado.",
        "status_quick_saved": "Guardado rápido (F3): {n} jugadas.",
        "status_quick_loaded": "Carga rápida (F4): {name}.",
        "status_menu_opened": "Menú {name} ({src}).",
        "title_quick_save": "Guardado rápido",
        "title_quick_load": "Carga rápida",
        "title_book": "Libro",
        "err_book_load": "No se pudo cargar el libro:\n{err}",
        "err_start_position": "No se pudo cargar la posición inicial:",
        "err_no_legal_move": "no hay jugada legal",
        "player_n": "Jugador {n}",
        "book_name_12": "12-ply-dist (victoria + jugadas hasta el final)",
        "set_menu_item": "Juego de fichas {no} – {name}",
        "acc_pgup": "Re Pág",
        "acc_pgdn": "Av Pág",
        "acc_up": "Arriba",
        "acc_down": "Abajo",
        "acc_left": "Izquierda",
        "acc_right": "Derecha",
        "match_title": "Partido Ordenador-Ordenador",
        "label_yellow": "Amarillo:",
        "label_red": "Rojo:",
        "match_games": "Partidas (1–10000):",
        "user_own_psw": " (p,s,w propios)",
        "match_hint": "p = % de jugadas perfectas (el resto son errores), s = protección contra la derrota (ningún error que pierda en <= s jugadas del rival), w = prioridad de victoria (una victoria en <= w jugadas va siempre primero).",
        "match_swap": "Cambiar de color tras cada partida",
        "match_tempo": "Velocidad:",
        "tempo_normal": "Normal",
        "tempo_fast": "Rápido",
        "tempo_turbo": "Solo resultados (Turbo)",
        "match_result_label": "Resultado final (copiable):",
        "match_status_line": "Partido Ordenador-Ordenador {nr}/{games} | Amarillo ({g}) - Rojo ({r}) | {score} | {elo}",
        "match_none": "Ningún partido activo.",
        "match_state_done": "Terminado.",
        "match_state_aborted": "Cancelado.",
        "match_state_running": "En curso...",
        "match_live": "Partida {nr}/{games} – {state}\nAmarillo ({g}) – Rojo ({r}): {score}  Elo {elo}",
        "match_no_result": "No se ha jugado ningún partido Ordenador-Ordenador.",
        "match_result_text": "{a} - {b} = {pg}-{pr} (+{w}/={d}/-{l})  Diferencia de Elo = {elo}\nPartidas: {done}/{games} ({state}), cambio de color: {swap}",
        "match_aborted_lc": "cancelado",
        "match_finished_lc": "terminado",
        "onoff_on": "sí",
        "onoff_off": "no",
        "match_ended_status": "Partido Ordenador-Ordenador terminado: {res}",
        "match_stopped_status": "Partido Ordenador-Ordenador detenido. {res}",
        "match_next_in": "  (Siguiente partida en 3 s ...)",
        "stand_head": "Humano vs {x}",
        "stand_head_default": "Humano vs Ordenador",
        "stand_sub": "(+{w}/={d}/-{l}) · {n} partidas",
        "side_computer": "Ordenador ({label})",
    },
    "nl": {
        # Nederlands (04.10.2026), bron: en
        "menu_file": "Bestand",
        "menu_view": "Weergave",
        "menu_settings": "Instellingen",
        "menu_commands": "Opdrachten",
        "menu_help": "Help",
        "new_game": "Nieuw spel",
        "new_random": "Nieuw met willekeurige stelling...",
        "load_position": "Stelling laden...",
        "save_position": "Stelling opslaan...",
        "quick_save": "Snel opslaan (F3)",
        "quick_load": "Snel laden (F4)",
        "quit": "Afsluiten",
        "ghost_stone": "Spooksteen",
        "drop_animation": "Valanimatie",
        "show_last_move": "Laatste zet tonen",
        "score_onoff": "Stand aan/uit",
        "score_reset": "Stand wissen",
        "computer_level": "Computerniveau",
        "human_computer": "Mens-computer",
        "two_player": "2 spelers (beide mens)",
        "selfplay": "Computer-computer (uitspelen)",
        "match": "Computer-computerwedstrijd...",
        "stop_autoplay": "Automatisch spel stoppen",
        "stone_set": "Steenset",
        "prev_set": "Vorige set",
        "next_set": "Volgende set",
        "first_move": "Eerste zet",
        "move_back": "Zet terug",
        "move_forward": "Zet vooruit",
        "last_move": "Laatste zet",
        "engine_move": "Zet (computer)",
        "score_all": "Alle zetten beoordelen (1x)",
        "permanent_analysis": "Permanente analyse",
        "help_contents": "Inhoud",
        "help_info": "Info",
        "lang_menu": "Taal",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_es": "Español",
        "lang_nl": "Nederlands",
        "lang_it": "Italiano",
        "info_turn": "Aan zet",
        "info_box": "Info",
        "info_move": "Zet",
        "info_level": "Niveau",
        "info_depth": "Diepte",
        "info_value": "Waarde",
        "info_nodes": "Knopen",
        "info_time": "Tijd",
        "info_nodes_per_sec": "Snelheid",
        "info_book": "Bron",
        "info_human": "Mens",
        "depth_full": "Volledig",
        "depth_book": "Boek",
        "depth_search": "Zoeken",
        "book_from_book": "Boek",
        "book_computed": "berekend",
        "score_box": "Stand",
        "score_on": "Aan/uit",
        "score_reset_btn": "Wissen",
        "level_human": "Mens",
        "btn_new": "Nieuw",
        "btn_first": "<<",
        "btn_back": "<",
        "btn_forward": ">",
        "btn_last": ">>",
        "btn_move": "Zet",
        "btn_analyze": "Analyseren",
        "file_open_title": "Stelling laden",
        "file_save_title": "Stelling opslaan",
        "file_filter_c4": "ConnectFour-stelling",
        "file_filter_all": "Alle",
        "error_title": "Fout",
        "info_title": "Info",
        "new_random_title": "Nieuw spel met willekeurige stelling",
        "new_random_stones": "Stenen op het bord:",
        "new_random_result": "Uitslag (speler aan zet):",
        "new_random_any": "Willekeurig",
        "new_random_win": "Winst",
        "new_random_draw": "Remise",
        "new_random_loss": "Verlies",
        "new_random_hint": "Winst/verlies wordt door de engine gecontroleerd.",
        "btn_ok": "OK",
        "btn_cancel": "Annuleren",
        "btn_close": "Sluiten",
        "btn_copy": "Kopiëren",
        "btn_start": "Start",
        "btn_stop": "Stop",
        "status_thinking": "Computer denkt na...",
        "status_computer_move": "Computer speelde {col} in {sec} s.",
        "status_aborted": "Afgebroken.",
        "status_stopped": "Gestopt (resultaat verworpen).",
        "status_wait_thinking": "Computer denkt nog na - even wachten.",
        "status_game_over_new": "Spel afgelopen - start een nieuw spel.",
        "status_column_full": "Kolom {col} is vol.",
        "status_match_running": "Computer-computerwedstrijd loopt - stop die eerst.",
        "status_selfplay_running": "Computer-computer loopt - kies eerst een andere modus.",
        "status_new_game": "Nieuw spel.",
        "status_no_position_found": "Geen passende stelling gevonden - probeer Willekeurig.",
        "status_search_random": "Willekeurige stelling zoeken ({n} stenen, {wish})...",
        "status_scores_off": "Beoordeling uit (1-7).",
        "status_analysis_off": "Analyse uit.",
        "status_book_loaded": "Boek: {book}.",
        "status_saved": "Opgeslagen: {path}",
        "status_loaded": "Geladen: {path}",
        "status_no_quicksave": "Niets opgeslagen (druk eerst op F3).",
        "status_set_changed": "Steenset {no} - {name}.",
        "status_level_changed": "Niveau: {label}.",
        "status_computer_error": "Computerfout: {err}",
        "status_discarded": "Verworpen: stelling is tijdens de berekening veranderd.",
        "status_load_stopped_thinking": "Computer denkt nog na - stop eerst, laad daarna.",
        "status_ready": "Gereed.",
        "status_selfplay_running_stop": "Computer-computer loopt - stop dit eerst.",
        "status_random_done": "Willekeurige stelling: {n} stenen ({wish}).",
        "status_eval_aborted": "Beoordeling afgebroken.",
        "status_game_end": "Spel afgelopen: {msg}",
        "msg_draw": "Remise!",
        "msg_wins": "{who} wint!",
        "color_yellow": "Geel",
        "color_red": "Rood",
        "value_draw": "Remise",
        "status_analysis_error": "Analysefout: {err}",
        "status_analysis_done": "Analyse: kolom {col} ({score:+d}) in {sec} s.",
        "status_selfplay_fixed": "Computer-computer (uitspelen): vast niveau.",
        "status_hc_level": "Mens-computer: {label}.",
        "status_hc_mode": "Modus mens-computer ({label}).",
        "status_selfplay_playing": "Computer-computer (uitspelen) is bezig...",
        "status_stop_before_match": "Stop eerst, stel daarna de wedstrijd in.",
        "status_removed_hash": "Verwijderd: geen hashtabel-knop meer.",
        "status_removed_gallery": "Galerij verwijderd - sets staan in het menu.",
        "status_two_player": "Modus 2 spelers.",
        "status_autoanalysis_off": "Permanente analyse uit (1-7).",
        "status_autoanalysis_on": "Permanente analyse aan.",
        "status_quick_saved": "Snel opgeslagen (F3): {n} zetten.",
        "status_quick_loaded": "Snel geladen (F4): {name}.",
        "status_menu_opened": "Menu {name} ({src}).",
        "title_quick_save": "Snel opslaan",
        "title_quick_load": "Snel laden",
        "title_book": "Boek",
        "err_book_load": "Het boek kon niet worden geladen:\n{err}",
        "err_start_position": "De beginstelling kon niet worden geladen:",
        "err_no_legal_move": "geen geldige zet",
        "player_n": "Speler {n}",
        "book_name_12": "12-ply-dist (winst + zetten tot het einde)",
        "set_menu_item": "Steenset {no} - {name}",
        "acc_pgup": "Page Up",
        "acc_pgdn": "Page Down",
        "acc_up": "Omhoog",
        "acc_down": "Omlaag",
        "acc_left": "Links",
        "acc_right": "Rechts",
        "match_title": "Computer-computerwedstrijd",
        "label_yellow": "Geel:",
        "label_red": "Rood:",
        "match_games": "Partijen (1-10000):",
        "user_own_psw": " (eigen p,s,w)",
        "match_hint": "p = % perfecte zetten (de rest zijn blunders), s = verliesbescherming (geen blunder die binnen <= s zetten van de tegenstander verliest), w = winstprioriteit (een winst binnen <= w zetten gaat altijd voor).",
        "match_swap": "Kleuren wisselen na elke partij",
        "match_tempo": "Tempo:",
        "tempo_normal": "Normaal",
        "tempo_fast": "Snel",
        "tempo_turbo": "Alleen resultaten (turbo)",
        "match_result_label": "Eindresultaat (kopieerbaar):",
        "match_status_line": "Computer-computerwedstrijd {nr}/{games} | Geel ({g}) - Rood ({r}) | {score} | {elo}",
        "match_none": "Geen wedstrijd actief.",
        "match_state_done": "Afgelopen.",
        "match_state_aborted": "Afgebroken.",
        "match_state_running": "Bezig...",
        "match_live": "Partij {nr}/{games} - {state}\nGeel ({g}) - Rood ({r}): {score}  Elo {elo}",
        "match_no_result": "Geen computer-computerwedstrijd gespeeld.",
        "match_result_text": "{a} - {b} = {pg}-{pr} (+{w}/={d}/-{l})  Elo-verschil = {elo}\nPartijen: {done}/{games} ({state}), kleurwissel: {swap}",
        "match_aborted_lc": "afgebroken",
        "match_finished_lc": "afgelopen",
        "onoff_on": "aan",
        "onoff_off": "uit",
        "match_ended_status": "Computer-computerwedstrijd afgelopen: {res}",
        "match_stopped_status": "Computer-computerwedstrijd gestopt. {res}",
        "match_next_in": "  (Volgende partij over 3 s ...)",
        "stand_head": "Mens tegen {x}",
        "stand_head_default": "Mens tegen computer",
        "stand_sub": "(+{w}/={d}/-{l}) · {n} partijen",
        "side_computer": "Computer ({label})",
    },
    "it": {
        "menu_file": "File",
        "menu_view": "Vista",
        "menu_settings": "Impostazioni",
        "menu_commands": "Comandi",
        "menu_help": "Aiuto",
        "new_game": "Nuova partita",
        "new_random": "Nuova con posizione casuale...",
        "load_position": "Carica posizione...",
        "save_position": "Salva posizione...",
        "quick_save": "Salvataggio rapido (F3)",
        "quick_load": "Caricamento rapido (F4)",
        "quit": "Esci",
        "ghost_stone": "Pietra fantasma",
        "drop_animation": "Animazione di caduta",
        "show_last_move": "Mostra ultima mossa",
        "score_onoff": "Punteggio sì/no",
        "score_reset": "Azzera punteggio",
        "computer_level": "Livello computer",
        "human_computer": "Umano-Computer",
        "two_player": "2 giocatori (entrambi umani)",
        "selfplay": "Computer-Computer (gioca)",
        "match": "Incontro Computer-Computer...",
        "stop_autoplay": "Interrompi gioco automatico",
        "stone_set": "Set di pietre",
        "prev_set": "Set precedente",
        "next_set": "Set successivo",
        "first_move": "Prima mossa",
        "move_back": "Mossa indietro",
        "move_forward": "Mossa avanti",
        "last_move": "Ultima mossa",
        "engine_move": "Mossa (computer)",
        "score_all": "Valuta tutte le mosse (1x)",
        "permanent_analysis": "Analisi permanente",
        "help_contents": "Contenuti",
        "help_info": "Info",
        "lang_menu": "Lingua",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "lang_fr": "Français",
        "lang_es": "Español",
        "lang_nl": "Nederlands",
        "lang_it": "Italiano",
        "info_turn": "Tocca a",
        "info_box": "Info",
        "info_move": "Mossa",
        "info_level": "Livello",
        "info_depth": "Profondità",
        "info_value": "Valore",
        "info_nodes": "Nodi",
        "info_time": "Tempo",
        "info_nodes_per_sec": "Velocità",
        "info_book": "Fonte",
        "info_human": "Umano",
        "depth_full": "Completa",
        "depth_book": "Libro",
        "depth_search": "Ricerca",
        "book_from_book": "Libro",
        "book_computed": "calcolato",
        "score_box": "Punteggio",
        "score_on": "Sì/No",
        "score_reset_btn": "Azzera",
        "level_human": "Umano",
        "btn_new": "Nuovo",
        "btn_first": "<<",
        "btn_back": "<",
        "btn_forward": ">",
        "btn_last": ">>",
        "btn_move": "Mossa",
        "btn_analyze": "Analizza",
        "file_open_title": "Carica posizione",
        "file_save_title": "Salva posizione",
        "file_filter_c4": "Posizione ConnectFour",
        "file_filter_all": "Tutti",
        "error_title": "Errore",
        "info_title": "Info",
        "new_random_title": "Nuova partita con posizione casuale",
        "new_random_stones": "Pietre sulla scacchiera:",
        "new_random_result": "Risultato (giocatore a cui tocca muovere):",
        "new_random_any": "Qualsiasi",
        "new_random_win": "Vittoria",
        "new_random_draw": "Pareggio",
        "new_random_loss": "Sconfitta",
        "new_random_hint": "Vittoria/sconfitta è controllata dal motore.",
        "btn_ok": "OK",
        "btn_cancel": "Annulla",
        "btn_close": "Chiudi",
        "btn_copy": "Copia",
        "btn_start": "Avvia",
        "btn_stop": "Ferma",
        "status_thinking": "Il computer sta pensando...",
        "status_computer_move": "Il computer ha giocato {col} in {sec} s.",
        "status_aborted": "Interrotto.",
        "status_stopped": "Fermato (risultato scartato).",
        "status_wait_thinking": "Il computer sta ancora pensando – attendere.",
        "status_game_over_new": "Partita finita – inizia una nuova partita.",
        "status_column_full": "La colonna {col} è piena.",
        "status_match_running": "L'incontro Computer-Computer è in corso – fermalo prima.",
        "status_selfplay_running": "Computer-Computer è in corso – scegli prima un'altra modalità.",
        "status_new_game": "Nuova partita.",
        "status_no_position_found": "Nessuna posizione adatta trovata – prova Qualsiasi.",
        "status_search_random": "Ricerca posizione casuale ({n} pietre, {wish})...",
        "status_scores_off": "Valutazioni spente (1-7).",
        "status_analysis_off": "Analisi spenta.",
        "status_book_loaded": "Libro: {book}.",
        "status_saved": "Salvato: {path}",
        "status_loaded": "Caricato: {path}",
        "status_no_quicksave": "Niente salvato (premi prima F3).",
        "status_set_changed": "Set di pietre {no} – {name}.",
        "status_level_changed": "Livello: {label}.",
        "status_computer_error": "Errore computer: {err}",
        "status_discarded": "Scartato: la posizione è cambiata durante il calcolo.",
        "status_load_stopped_thinking": "Il computer sta ancora pensando – fermalo prima, poi carica.",
        "status_ready": "Pronto.",
        "status_selfplay_running_stop": "Computer-Computer è in corso – fermalo prima.",
        "status_random_done": "Posizione casuale: {n} pietre ({wish}).",
        "status_eval_aborted": "Valutazione interrotta.",
        "status_game_end": "Partita finita: {msg}",
        "msg_draw": "Pareggio!",
        "msg_wins": "{who} vince!",
        "color_yellow": "Giallo",
        "color_red": "Rosso",
        "value_draw": "Pareggio",
        "status_analysis_error": "Errore di analisi: {err}",
        "status_analysis_done": "Analisi: colonna {col} ({score:+d}) in {sec} s.",
        "status_selfplay_fixed": "Computer-Computer (gioca): livello fisso.",
        "status_hc_level": "Umano-Computer: {label}.",
        "status_hc_mode": "Modalità umano-computer ({label}).",
        "status_selfplay_playing": "Computer-Computer (gioca) sta giocando...",
        "status_stop_before_match": "Ferma prima, poi imposta l'incontro.",
        "status_removed_hash": "Rimosso: niente più pulsante per la tabella hash.",
        "status_removed_gallery": "Galleria rimossa – i set sono nel menu.",
        "status_two_player": "Modalità 2 giocatori.",
        "status_autoanalysis_off": "Analisi permanente spenta (1-7).",
        "status_autoanalysis_on": "Analisi permanente accesa.",
        "status_quick_saved": "Salvataggio rapido (F3): {n} mosse.",
        "status_quick_loaded": "Caricamento rapido (F4): {name}.",
        "status_menu_opened": "Menu {name} ({src}).",
        "title_quick_save": "Salvataggio rapido",
        "title_quick_load": "Caricamento rapido",
        "title_book": "Libro",
        "err_book_load": "Il libro non può essere caricato:\n{err}",
        "err_start_position": "La posizione iniziale non può essere caricata:",
        "err_no_legal_move": "nessuna mossa legale",
        "player_n": "Giocatore {n}",
        "book_name_12": "12-ply-dist (vittoria + mosse fino alla fine)",
        "set_menu_item": "Set di pietre {no} – {name}",
        "acc_pgup": "PagSu",
        "acc_pgdn": "PagGiù",
        "acc_up": "Su",
        "acc_down": "Giù",
        "acc_left": "Sinistra",
        "acc_right": "Destra",
        "match_title": "Incontro Computer-Computer",
        "label_yellow": "Giallo:",
        "label_red": "Rosso:",
        "match_games": "Partite (1–10000):",
        "user_own_psw": " (p,s,w propri)",
        "match_hint": "p = % mosse perfette (il resto sono errori), s = protezione contro le sconfitte (nessun errore che perde entro <= s mosse dell'avversario), w = priorità alle vittorie (una vittoria entro <= w mosse viene sempre giocata per prima).",
        "match_swap": "Scambia i colori dopo ogni partita",
        "match_tempo": "Velocità:",
        "tempo_normal": "Normale",
        "tempo_fast": "Veloce",
        "tempo_turbo": "Solo risultati (Turbo)",
        "match_result_label": "Risultato finale (copiabile):",
        "match_status_line": "Incontro Computer-Computer {nr}/{games} | Giallo ({g}) - Rosso ({r}) | {score} | {elo}",
        "match_none": "Nessun incontro attivo.",
        "match_state_done": "Finito.",
        "match_state_aborted": "Interrotto.",
        "match_state_running": "In corso...",
        "match_live": "Partita {nr}/{games} – {state}\nGiallo ({g}) – Rosso ({r}): {score}  Elo {elo}",
        "match_no_result": "Nessun incontro Computer-Computer giocato.",
        "match_result_text": "{a} - {b} = {pg}-{pr} (+{w}/={d}/-{l})  Differenza Elo = {elo}\nPartite: {done}/{games} ({state}), scambio colori: {swap}",
        "match_aborted_lc": "interrotto",
        "match_finished_lc": "finito",
        "onoff_on": "acceso",
        "onoff_off": "spento",
        "match_ended_status": "Incontro Computer-Computer finito: {res}",
        "match_stopped_status": "Incontro Computer-Computer fermato. {res}",
        "match_next_in": "  (Prossima partita tra 3 s ...)",
        "stand_head": "Umano contro {x}",
        "stand_head_default": "Umano contro Computer",
        "stand_sub": "(+{w}/={d}/-{l}) · {n} partite",
        "side_computer": "Computer ({label})",
    },
}

# Stufennamen (ohne Nummer) je Sprache; Schlüssel wie cfs_levels.STUFEN_ORDER.
LEVEL_NAMES = {
    "de": {"verlierer": "Verlierer", "zufall": "Zufall",
           "sehr_leicht": "Sehr Leicht", "leicht": "Leicht",
           "anfaenger": "Anfänger", "fortgeschritten": "Fortgeschritten",
           "taktiker": "Taktiker", "mittel": "Mittel",
           "fordernd": "Fordernd", "schwer": "Schwer",
           "sehr_schwer": "Sehr Schwer", "experte": "Experte",
           "meister": "Meister", "starker_meister": "Starker Meister",
           "perfekt": "Perfekt"},
    "en": {"verlierer": "Loser", "zufall": "Random",
           "sehr_leicht": "Very Easy", "leicht": "Easy",
           "anfaenger": "Beginner", "fortgeschritten": "Advanced",
           "taktiker": "Tactician", "mittel": "Intermediate",
           "fordernd": "Demanding", "schwer": "Hard",
           "sehr_schwer": "Very Hard", "experte": "Expert",
           "meister": "Master", "starker_meister": "Strong Master",
           "perfekt": "Perfect"},
    "es": {"verlierer": "Perdedor", "zufall": "Aleatorio",
           "sehr_leicht": "Muy fácil", "leicht": "Fácil",
           "anfaenger": "Principiante", "fortgeschritten": "Avanzado",
           "taktiker": "Táctico", "mittel": "Intermedio",
           "fordernd": "Exigente", "schwer": "Difícil",
           "sehr_schwer": "Muy difícil", "experte": "Experto",
           "meister": "Maestro", "starker_meister": "Maestro fuerte",
           "perfekt": "Perfecto"},
    "fr": {"verlierer": "Perdant", "zufall": "Aléatoire",
           "sehr_leicht": "Très facile", "leicht": "Facile",
           "anfaenger": "Débutant", "fortgeschritten": "Avancé",
           "taktiker": "Tacticien", "mittel": "Intermédiaire",
           "fordernd": "Exigeant", "schwer": "Difficile",
           "sehr_schwer": "Très difficile", "experte": "Expert",
           "meister": "Maître", "starker_meister": "Maître supérieur",
           "perfekt": "Parfait"},
    "nl": {"verlierer": "Verliezer", "zufall": "Willekeurig",
           "sehr_leicht": "Zeer makkelijk", "leicht": "Makkelijk",
           "anfaenger": "Beginner", "fortgeschritten": "Gevorderd",
           "taktiker": "Tacticus", "mittel": "Gemiddeld",
           "fordernd": "Veeleisend", "schwer": "Moeilijk",
           "sehr_schwer": "Zeer moeilijk", "experte": "Expert",
           "meister": "Meester", "starker_meister": "Sterke meester",
           "perfekt": "Perfect"},
    "it": {"verlierer": "Perdente", "zufall": "Casuale",
           "sehr_leicht": "Molto facile", "leicht": "Facile",
           "anfaenger": "Principiante", "fortgeschritten": "Avanzato",
           "taktiker": "Tattico", "mittel": "Intermedio",
           "fordernd": "Impegnativo", "schwer": "Difficile",
           "sehr_schwer": "Molto difficile", "experte": "Esperto",
           "meister": "Maestro", "starker_meister": "Maestro forte",
           "perfekt": "Perfetto"},
}

DEFAULT_LANG = "de"
LANG = DEFAULT_LANG

# Alle geplanten Sprachen (Menü zeigt alle, Fallback Deutsch solange
# keine Übersetzung vorliegt — Stand 04.10.2026: de/en/es/fr/nl aktiv).
LANG_ORDER = ("de", "en", "fr", "es", "nl", "it")
LANG_LABEL_KEY = {"de": "lang_de", "en": "lang_en", "fr": "lang_fr",
                  "es": "lang_es", "nl": "lang_nl", "it": "lang_it"}


def _lang_cfg_path():
    """lang.cfg im Benutzerordner (CFS_USER_DIR bzw. ~/.config/...)."""
    from cfs_core import paths
    return os.path.join(paths.user_dir(), "lang.cfg")


def _system_lang():
    """Systemsprache als Kuerzel ('en', 'de', ...) oder ''."""
    import locale
    for var in ("LC_ALL", "LC_MESSAGES", "LANG", "LANGUAGE"):
        v = os.environ.get(var, "")
        if v and v not in ("C", "POSIX", "C.UTF-8"):
            return v.split(":")[0][:2].lower()
    try:
        loc = locale.getlocale()[0] or ""
    except Exception:
        loc = ""
    return loc[:2].lower()


def detect_start_lang():
    """Startsprache: gespeicherte Wahl > Systemsprache (en/* -> en,
    sonst de). Nur Codes mit echten Inhalten (nicht-leeres Dict)."""
    try:
        with open(_lang_cfg_path(), encoding="utf-8") as f:
            code = f.read().strip().lower()[:2]
        if code in STRINGS and STRINGS[code]:
            return code
    except Exception:
        pass
    if _system_lang().startswith("en"):
        return "en" if STRINGS.get("en") else DEFAULT_LANG
    return DEFAULT_LANG


def save_start_lang(code):
    """Sprachwahl merken (lang.cfg im Benutzerordner). Fehler ignorieren."""
    try:
        with open(_lang_cfg_path(), "w", encoding="utf-8") as f:
            f.write(code.strip().lower()[:2])
    except Exception:
        pass


def set_lang(code):
    """Aktive Sprache umschalten ('de'/'en'). Gibt True bei Erfolg."""
    global LANG
    if code in STRINGS:
        LANG = code
        return True
    return False


def t(key, lang=None):
    """Text für Schlüssel holen, Fallback Deutsch, dann Schlüssel."""
    code = lang or LANG
    d = STRINGS.get(code, STRINGS[DEFAULT_LANG])
    if key in d:
        return d[key]
    return STRINGS[DEFAULT_LANG].get(key, key)


def tf(key, lang=None, **kw):
    """Text holen und {Platzhalter} füllen (Fehler -> unformatierter Text)."""
    txt = t(key, lang)
    try:
        return txt.format(**kw)
    except Exception:
        return txt


def level_name(key, lang=None):
    """Stufenname (ohne Nummer) in der aktiven Sprache, Fallback Deutsch."""
    names = LEVEL_NAMES.get(lang or LANG, LEVEL_NAMES[DEFAULT_LANG])
    return names.get(key, LEVEL_NAMES[DEFAULT_LANG].get(key, key))


def fmt_thousands(n, lang=None):
    """Ganzzahl mit Tausendertrenner (de: Punkt, sonst Komma)."""
    code = lang or LANG
    sep = "." if code in ("de", "es", "nl", "it") else (" " if code == "fr" else ",")
    return f"{int(n):,d}".replace(",", sep)


def fmt_decimal(txt, lang=None):
    """Dezimalpunkt-Text ('2.3') in die Landesschreibweise (de: Komma)."""
    return txt.replace(".", ",") if (lang or LANG) in ("de", "es", "fr", "nl", "it") else txt
